sudo: required

script:
  - bash -xve ./test/travis_ros_install.bash
  - source ~/catkin_ws/devel/setup.bash
  - bash -xve ./test/travis_package_make.bash
  - source ~/catkin_ws/devel/setup.bash
  - rostest pimouse_ros test.launch


language: python
virtualenv:
  system_site_packages: true